### ISSUE TITLE
Unable to create OpenShift Containers using Fuse in OpenShift Online

### ISSUE THREAD

**Issue by luciddreamz** [jboss-fuse/fuse-openshift-cartridge#70]
Fabric8's OpenShiftContainerProvider.create method appears to be attempting to create new Fuse conatainers on OpenShift Online by referencing the Fuse cartridge name (in this case 'fuse-6.1.1'). Fuse is not installed in OpenShift Online and cannot be referenced by name when creating a new container. Instead, a URL to the cartridge manifest should be provided, as in 'https://raw.githubusercontent.com/jboss-fuse/fuse-openshift-cartridge/master/metadata/manifest.yml'.

![screen shot 2015-10-03 at 1 17 32 pm](https://cloud.githubusercontent.com/assets/928421/10264331/47b53376-69d6-11e5-8bfa-cde8cc838b23.png)

**Comment by jamesfalkner** [comment]
In the GUI one can workaround this via the Wiki tab, navigating to `root/fabric/profiles/openshift.profile/io.fabric8.openshift.properties` and overriding the `default.cartridge.url` setting as shown.
![screen shot 2016-03-03 at 11 43 08 am](https://cloud.githubusercontent.com/assets/861894/13501785/0044d7e4-e136-11e5-9bf7-100f59c2a618.png)
